In [ ]:
import numpy as np

In [ ]:
Установить, какие произведения матриц АВ и  ВА определены, и найти размерности полученных матриц:

а)  А — матрица 4*2 ,  В — матрица 4*2;

б)  А — матрица 2*5 ,  В — матрица 5*3;

в)  А — матрица 8*3 ,  В — матрица 3*8;

г)  А — квадратная матрица 4*4,  В — квадратная матрица 4*4.

Вариант a:

 А*В = 4*2 и 4*2

 В*А = 4*2 и 4*2

Произведения не определены

Вариант б:

А*В = 2*5 и 5*3, произведение определено, размерность полученной матрицы 2*3

В*А = 5*3 и 2*5, произведение не определено

Вариант в:

 А*В = 8*3 и 3*8, произведение определено, размерность полученной матрицы 8*8

 В*А = 3*8 и 8*3, произведение определено, размерность полученной матрицы 3*3

Вариант г:

А*В, В*А,  - оба произведения определены, размерность полученной матрицы 4*4

In [ ]:
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0,5]])
result2_1 = a + b
result2_1

array([[ 5, -3],
       [ 3,  5]])

In [ ]:
result2_2 = np.dot(a, b)
result2_2

array([[  4, -11],
       [ 12,  -3]])

In [ ]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
result3 = (3 * a) + (-2 * b) + (4 * c)
result3

array([[ 11,  -5],
       [  9, -12]])

In [ ]:
a = np.array([[4,1], [5,-2], [2,3]])
aT = a.T
aT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [ ]:
result4_1 = np.dot(a, aT)
result4_1

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [ ]:
result4_2 = np.dot(aT, a)
result4_2


array([[45,  0],
       [ 0, 14]])